<?php

namespace App\Controllers;

use App\Models\Article;

class Index extends \App\Controller
{
    protected function access($action)
    {
        return parent::access($action); // TODO: Change the autogenerated stub
        //return false;
    }

    protected function actionDefault()
    {
        $this->view->title = 'Новости';
        $this->view->news = Article::findAll();
        $this->view->display(__DIR__ . '/../../templates/default.php');
    }
}