<?php

namespace App\Controllers;

class Index
    //extends \App\Controller
{
    /*
    protected function access($action)
    {
        return parent::access($action); // TODO: Change the autogenerated stub
        //return false;
    }
*/
    //protected function actionDefault()
    public function actionDefault()
    {
        /*
        $this->view->title = 'Новости';
        $this->view->news = Article::findAll();
        $this->view->display(__DIR__ . '/../../templates/default.php');
        */
        $view = new \App\View();
        $view->title = 'Новости';
        $view->news = \App\Models\Article::findAll();
        $view->display(__DIR__ . '/../../templates/default.php');
    }
}