<?php

namespace App\Controllers;

use App\Models\Article;

class Index extends \App\Controller
{
    protected function access($action)
    {
        return parent::access($action); // TODO: Change the autogenerated stub
        //return false;
    }

    protected function actionOne()
    {
        $this->view->title = 'Новость';
        $this->view->article = Article::findById($_GET['id']);
        $this->view->display(__DIR__ . '/../../templates/article.php');
    }
}